<template>
<div id="sp-modal-menu-wrap">
    <ul id="sp-modal-menu">
        <li><a href="">Kitchen</a></li>
        <li><a href="">Bar</a></li>
        <li><a href="">Labo</a></li>
        <li><a href="">Rooms</a></li>
        <li><a href="">Access</a></li>
    </ul>
</div>
</template>

<style>
    #sp-modal-menu-wrap {position: fixed; top:0; left:0; right:0; box-shadow: 2px 2px 10px rgba(0,0,0,0.2); background: #fff;}
    #sp-modal-menu {text-align: center;}
    #sp-modal-menu ul li a {color: #000; display: inline-block;padding: 10px;}

    @media screen and (min-width: 720px){

    }
</style>